# -*- coding: utf-8 -*-
"""Chapter 4: Data Transformation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z3hOJFvWecRd2TIGIPwVN10K9agcDzTf
"""

import pandas as pd
import numpy as np

!pip install Faker
fake = Faker('en_US')

import csv
import random
from faker import Faker
import datetime

account = [123456789, 123456788, 123456787, 123456786, 123456785, 123456784, 123456783, 123456782, 123456781, 123456780, 123456779, 123456778, 123456777, 123456776, 123456775, 123456774, 123456773, 123456772, 123456771, 123456770]
name = ["SAS Web Tec", "Kirlosker Service Center", "Will LLC", "Kulas Inc", "ABC Dogma", "Gen Power", "Super Sexy Dingo", "My SQ Man", "Name IT", "GitHub", "Loolo INC", "Pryianka Ji"]
order = [99999, 99998, 99997, 99996, 99995, 99994, 99993, 99992, 99991, 99990, 99989, 99987, 99986, 99985, 99985, 99983, 99982, 99981, 99980]
sku = ['s1-supercomputer', 's2-supercomputer', 's3-supercomputer', 's4-supercomputer', 's5-supercomputer', 's6-supercomputer', 's7-supercomputer', 's8-supercomputer', 's9-supercomputer', 's10-supercomputer', 's11-supercomputer']


def datagenerate(records, headers):
    fake = Faker('en_US')
    with open("sales.csv", 'wt') as csvFile:
        writer = csv.DictWriter(csvFile, fieldnames=headers)
        writer.writeheader()
        for i in range(records):
            accounts = random.choice(account)
            names = random.choice(name)
            orders = random.choice(order)
            skus = random.choice(sku)

            writer.writerow({
                    "Account" : accounts,
                    "Company" : names,
                    "Order": orders,
                    "SKU" : skus,
                    "Country" : fake.country(),
                    "Year": fake.year(),
                    "Quantity" : fake.pyint(min_value=0, max_value=9999, step=1),
                    "UnitPrice" : fake.pyint(min_value=10, max_value=700, step=1),
                    'transactionComplete': fake.pybool(),
                    })
    
if __name__ == '__main__':
    records = 10000
    headers = ["Account", "Company", "Order", "SKU", "Country", "Year",
               "Quantity", "UnitPrice", "transactionComplete"]
    datagenerate(records, headers)
    print("CSV generation complete!")